-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'CHAT_MESSAGE';
ALTER TYPE "NotificationType" ADD VALUE 'ACHIEVEMENT_UNLOCKED';
ALTER TYPE "NotificationType" ADD VALUE 'JOURNAL_COMMENT';
ALTER TYPE "NotificationType" ADD VALUE 'RECOMMENDATION_ADDED';
ALTER TYPE "NotificationType" ADD VALUE 'NEW_APPOINTMENT';
ALTER TYPE "NotificationType" ADD VALUE 'NEW_CONSULTATION';
ALTER TYPE "NotificationType" ADD VALUE 'NEW_REVIEW';
ALTER TYPE "NotificationType" ADD VALUE 'BROADCAST';

-- AlterTable
ALTER TABLE "Notification" ADD COLUMN "url" TEXT;
